version: '3.5'

volumes:
  # directory for TLS certs and other permanent files used by caddy
  caddy-data:
  # directory for caddy configuration
  caddy-config:
  caddy-react-files:
  caddy-transaction-service-files:

services:
  lb:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile.${GNOSIS_SAFE_ENVIRONMENT:-local}:/etc/caddy/Caddyfile:ro"
      - caddy-react-files:/srv/gnosis-safe-react
      - caddy-transaction-service-files:/srv/gnosis-safe-transaction-service
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - react
      - transaction-service-web

  redis:
    image: redis:alpine

  transaction-service-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres

  transaction-service-worker: &transaction-service-worker
    build:
      context: ./vendor/github.com/gnosis/safe-transaction-service/
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - configs/gnosis-safe-transaction-service.env
    depends_on:
      - transaction-service-db
      - redis
    command: docker/web/celery/worker/run.sh

  transaction-service-scheduler:
    <<: *transaction-service-worker
    command: docker/web/celery/scheduler/run.sh

  transaction-service-web:
    <<: *transaction-service-worker
    working_dir: /app
    ports:
      - "17000:8888"
    volumes:
      # the folder name nginx is hard-coded in the run script
      - caddy-transaction-service-files:/nginx
    command: docker/web/run_web.sh

  client-gateway-web:
    build:
      context: ./vendor/github.com/gnosis/safe-client-gateway/
    env_file:
      - configs/gnosis-safe-client-gateway.env
    depends_on:
      - redis
    ports:
      - "17001:3666"

  react:
    build:
      context: ./docker-gnosis-safe-react
      args:
        - REACT_APP_NETWORK=$REACT_APP_NETWORK
        - REACT_APP_IPFS_GATEWAY=$REACT_APP_IPFS_GATEWAY
        - REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS=$REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS
        - REACT_APP_SAFE_URL=$REACT_APP_SAFE_URL
        - REACT_APP_CLIENT_GATEWAY_URL=$REACT_APP_CLIENT_GATEWAY_URL
        - REACT_APP_TRANSACTION_SERVICE_URL=$REACT_APP_TRANSACTION_SERVICE_URL
    volumes:
      - caddy-react-files:/app/build
