version: '3.5'

networks:
  gnosis_safe_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  # directory for TLS certs and other permanent files used by caddy
  caddy-data:
  # directory for caddy configuration
  caddy-config:
  caddy-react-files:
  caddy-transaction-service-files:
  caddy-config-service-files:
  # directory for persistent transaction service data
  transaction-service-data:
  # directory for persistent config service data
  config-service-data:

services:
  lb:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:17000:17000"
      - "127.0.0.1:17001:17001"
      - "127.0.0.1:17002:17002"
      - "127.0.0.1:17007:17007"
    environment:
      GNOSIS_SAFE_DOMAIN: "${GNOSIS_SAFE_DOMAIN}"
    volumes:
      - "./Caddyfile.${GNOSIS_SAFE_ENVIRONMENT}:/etc/caddy/Caddyfile:ro"
      - caddy-react-files:/srv/gnosis-safe-react
      - caddy-transaction-service-files:/srv/gnosis-safe-transaction-service
      - caddy-config-service-files:/srv/gnosis-safe-config-service
      - caddy-data:/data
      - caddy-config:/config
    networks:
      gnosis_safe_net:
    depends_on:
      - react
      - transaction-service-web
      - config-service-web

  transaction-service-redis:
    image: redis:alpine
    networks:
      gnosis_safe_net:

  transaction-service-db:
    image: postgres:alpine
    volumes:
      - transaction-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      gnosis_safe_net:

  transaction-service-worker: &transaction-service-worker
    build:
      context: ./vendor/github.com/gnosis/safe-transaction-service/
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - "configs/gnosis-safe-transaction-service.env.${GNOSIS_SAFE_ENVIRONMENT}"
    depends_on:
      - transaction-service-db
      - transaction-service-redis
    networks:
      gnosis_safe_net:
    command: docker/web/celery/worker/run.sh

  transaction-service-scheduler:
    <<: *transaction-service-worker
    command: docker/web/celery/scheduler/run.sh

  transaction-service-web:
    <<: *transaction-service-worker
    working_dir: /app
    ports:
      - "8888"
    volumes:
      # the folder name nginx is hard-coded in the run script
      - caddy-transaction-service-files:/nginx
    networks:
      gnosis_safe_net:
        ipv4_address: 172.16.238.100
    command: docker/web/run_web.sh

  client-gateway-redis:
    image: redis:alpine
    networks:
      gnosis_safe_net:

  client-gateway-web:
    build:
      context: ./vendor/github.com/gnosis/safe-client-gateway/
    ports:
      - "3666"
    env_file:
      - "configs/gnosis-safe-client-gateway.env.${GNOSIS_SAFE_ENVIRONMENT}"
    depends_on:
      - client-gateway-redis
      - config-service-web
      - transaction-service-web
    networks:
      gnosis_safe_net:
    links:
      - "config-service-web:configserviceweb"
      - "transaction-service-web:transactionserviceweb"

  react:
    build:
      context: ./docker-gnosis-safe-react
      args:
        - REACT_APP_NETWORK=$REACT_APP_NETWORK
        - REACT_APP_IPFS_GATEWAY=$REACT_APP_IPFS_GATEWAY
        - REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS=$REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS
        - REACT_APP_SAFE_URL=$REACT_APP_SAFE_URL
        - REACT_APP_CLIENT_GATEWAY_URL=$REACT_APP_CLIENT_GATEWAY_URL
        - REACT_APP_TRANSACTION_SERVICE_URL=$REACT_APP_TRANSACTION_SERVICE_URL
    volumes:
      - caddy-react-files:/app/build
    networks:
      gnosis_safe_net:

  config-service-db:
    image: postgres:alpine
    volumes:
      - config-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      gnosis_safe_net:

  config-service-web:
    build:
      context: ./vendor/github.com/gnosis/safe-config-service/
    ports:
      - "8000"
    env_file:
      - "configs/gnosis-safe-config-service.env.${GNOSIS_SAFE_ENVIRONMENT}"
    volumes:
      - caddy-config-service-files:/nginx
    networks:
      gnosis_safe_net:
    depends_on:
      - config-service-db
