version: '3.8'

services:
  caddy:
    ports:
      - "80:80"
      - "443:443"
    environment:
      GNOSIS_SAFE_SUPPORT_EMAIL: "${GNOSIS_SAFE_SUPPORT_EMAIL}"
      GNOSIS_SAFE_DOMAIN: "${GNOSIS_SAFE_DOMAIN}"
    volumes:
      - "./Caddyfile.production:/etc/caddy/Caddyfile:ro"

  transaction-service-worker:
    env_file:
      - "configs/gnosis-safe-transaction-service.env.production"

  client-gateway-web:
    env_file:
      - "configs/gnosis-safe-client-gateway.env.production"

  config-service-web:
    env_file:
      - "configs/gnosis-safe-config-service.env.production"
