version: '3.5'

volumes:
  gnosis-safe-nginx-shared:
  caddy-data:
  caddy-config:
  caddy-gnosis-safe-react:

services:
  gnosis-safe-lb:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile.${CADDY_CFG_TYPE:-production}:/etc/caddy/Caddyfile:ro"
      - caddy-gnosis-safe-react:/srv/gnosis-safe-react
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - gnosis-safe-react

  gnosis-safe-nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./vendor/github.com/gnosis/safe-transaction-service/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - gnosis-safe-nginx-shared:/nginx
    depends_on:
      - gnosis-safe-transaction-service-web

  gnosis-safe-redis:
    image: redis:alpine

  gnosis-safe-transaction-service-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres

  gnosis-safe-transaction-service-worker: &gnosis-safe-transaction-service-worker
    build:
      context: ./vendor/github.com/gnosis/safe-transaction-service/
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - configs/gnosis-safe-transaction-service.env
    depends_on:
      - gnosis-safe-transaction-service-db
      - gnosis-safe-redis
    command: docker/web/celery/worker/run.sh

  gnosis-safe-transaction-service-scheduler:
    <<: *gnosis-safe-transaction-service-worker
    command: docker/web/celery/scheduler/run.sh

  gnosis-safe-transaction-service-web:
    <<: *gnosis-safe-transaction-service-worker
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - gnosis-safe-nginx-shared:/nginx
    command: docker/web/run_web.sh

  gnosis-safe-client-gateway-web:
    build:
      context: ./vendor/github.com/gnosis/safe-client-gateway/
    env_file:
      - configs/gnosis-safe-client-gateway.env
    depends_on:
      - gnosis-safe-redis
    ports:
      - "3666:3666"

  gnosis-safe-react:
    build:
      context: ./docker-gnosis-safe-react
      args:
        - REACT_APP_NETWORK=$REACT_APP_NETWORK
        - REACT_APP_IPFS_GATEWAY=$REACT_APP_IPFS_GATEWAY
        - REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS=$REACT_APP_SPENDING_LIMIT_MODULE_ADDRESS
        - REACT_APP_SAFE_URL=$REACT_APP_SAFE_URL
        - REACT_APP_CLIENT_GATEWAY_URL=$REACT_APP_CLIENT_GATEWAY_URL
        - REACT_APP_TRANSACTION_SERVICE_URL=$REACT_APP_TRANSACTION_SERVICE_URL
    volumes:
      - caddy-gnosis-safe-react:/app/build
